name: MemberPress Deployer

on:
  push:
    branches:
      - deployer
  schedule:
    - cron: '0 10 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Deployer
      uses: actions/checkout@v2

    - name: Checkout MemberPress
      uses: actions/checkout@v2
      with:
        ref: main
        path: repositories/memberpress

    - name: deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        MEMBERPRESS_LICENSE_KEY: ${{ secrets.MEMBERPRESS_LICENSE_KEY }}
        MEMBERPRESS_LICENSE_DOMAIN: ${{ secrets.MEMBERPRESS_LICENSE_DOMAIN }}
      run: bin/memberpress-deployer
