name: MemberPress Deployer

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6

    - name: deploy
      env:
        MEMBERPRESS_LICENSE_KEY: ${{ secrets.MEMBERPRESS_LICENSE_KEY }}
        MEMBERPRESS_LICENSE_DOMAIN: ${{ secrets.MEMBERPRESS_LICENSE_DOMAIN }}
      run: bin/memberpress-deployer
